### ISSUE TITLE
How do i get all Auth keys?

### ISSUE THREAD

**Issue by Tasluf665** [shahriar-shojib/bkash-payment-gateway#110]
key: 'abcdxx2369',
username: 'bkashTest',
password: 'bkashPassword1',
secret: 'bkashSup3rS3cRet',

How do I get all these keys for my merchant account? Is there any demo version that I can use for testing without having these keys?

Thank you.

**Comment by shahriar-shojib** [comment]
You will need to get in touch with bkash to get both testing and production credentials.
Unfortunately, I do not have any testing accounts.

**Comment by Tasluf665** [comment]
Thank you so much for responding so quickly.
I had already try to contact with bkash. I asked them to give the Auth keys for testing in the live chat. Although I have already a Merchant account. But they said my account doesn't have that options even for just testing.

I think it will be helpful for developers if we have this sandbox without having any Auth restrictions for testing. 
But Thank you again.
