### ISSUE TITLE
TypeError: BkashGateway is not a constructor

### ISSUE THREAD

**Issue by khokonm** [shahriar-shojib/bkash-payment-gateway#126]
Got this error when I tried to implement the project as per your instruction on the readme, just like the one I got while setting up nagad-payment-gateway.

**Comment by Nargis21** [comment]
I also face the same problem to integrate bkash payment gateway, did you get any solution?

**Comment by khokonm** [comment]
No, I had to read the bkash documentation and build my own solution.

**Comment by shahriar-shojib** [comment]
try importing like this
```
const { BkashGateway } = require('bkash-payment-gateway');
```

I updated the README with new import syntax

**Comment by Nargis21** [comment]
Okay, It's working, Thank you!
