### ISSUE TITLE
TypeError: BkashGateway is not a constructor -- bkash payment integration

### ISSUE THREAD

**Issue by Nargis21** [shahriar-shojib/bkash-payment-gateway#127]
I got this error when want to get "BkashGateway" and require "[bkash-payment-gateway](https://github.com/shahriar-shojib/bkash-payment-gateway/tree/main)" package

**Comment by shahriar-shojib** [comment]
try importing like this
```
const { BkashGateway } = require('bkash-payment-gateway');
```

I updated the README with new import syntax
